// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MSIT153Site.Models;

public partial class Members
{
    public int MemberId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public int? Age { get; set; }

    public string FileName { get; set; }

    public byte[] FileData { get; set; }
}